service: laravel-app

provider:
  name: aws
  region: us-east-1
  runtime: provided.al2

  environment:
    APP_KEY: base64:WtLRoKJwjjsbor2OnuJwzib06iraN4IDpyoQyYivU9E=
    APP_DEBUG: true
    APP_URL: https://ctp1wzzdtf.execute-api.us-east-1.amazonaws.com

    # Mail configuration
    MAIL_DRIVER: ses
    MAIL_MAILER: ses

    # Session and CORS settings
    SESSION_DRIVER: file
    SESSION_DOMAIN: http://localhost:3000,https://songdis.com
    SESSION_SECURE_COOKIE: true
    SESSION_LIFETIME: 120
    SANCTUM_STATEFUL_DOMAINS: http://localhost:3000,https://songdis.com

    # Database configuration
    DB_CONNECTION: mysql
    DB_HOST: ${env.DB_HOST}
    DB_PORT: ${env.DB_PORT}
    DB_DATABASE: ${env.DB_DATABASE}
    DB_USERNAME: ${env.DB_USERNAME}
    DB_PASSWORD: ${env.DB_PASSWORD}
    # DB_SSL_CERT: /var/task/storage/certs/aiven-ca.pem

functions:
  web:
    handler: public/index.php
    timeout: 130
    memorySize: 1024
    layers:
      - 'arn:aws:lambda:us-east-1:959512994844:layer:vapor-php-83al2:10'
    events:
      - httpApi: '*'

plugins:
  - ./vendor/bref/bref

# package:
#    include:
#     - vendor/**/*
#     - bootstrap/cache/**/*
#    exclude:
#     - node_modules/**
#     - tests/**
#     - vendor/**/.git
#     - storage/debugbar/**
#     - .gitignore
#     - .env
#     - README.md
#     - docker-compose.yml
