name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        tools: composer

    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Set execute permissions for migrate.sh
      run: chmod +x scripts/migrate.sh

    - name: Run Database Migrations
      run: ./scripts/migrate.sh

    - name: Deploy to AWS Lambda
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET: ${{secrets.AWS_BUCKET }}
        AWS_USE_PATH_STYLE_ENDPOINT: ${{secrets.AWS_USE_PATH_STYLE_ENDPOINT }}
        AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION }}
        DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        npm install -g serverless
        serverless deploy
        ./scripts/migrate.sh
